version: "3.8"
services:
  database:
    image: postgres:15-alpine
    container_name: cli-chat-app
    restart: always
    environment:
      POSTGRES_DB: "chat_app"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  data:
